var sports = [
  { name: "Basketball", image: "Basketball.jpg", video: "oyjYgmsM00Q" },
  { name: "Soccer", image: "Soccer.webp", video: "cTCgU4Vz0rE" },
];
/*
"Swimming",
"Water polo",
"Kayaking",
"Biking",
"Gymnastics",
"Volleyball",
"Wrestling",
"Baseball",
"Softball",
"Archery",
"Badminton",
"Boxing",
"Fencing",
"Field hockey",
"Football",
"Golf",
"Handball",
"Judo",
"Karate",
"Rowing",
"Skateboarding",
"Rock climbing",
"Table tennis",
"Taekwondo",
"Tennis",
"Rugby",
"Cricket",
"Lacrosse",
"Figure skating",
"Ice hockey",
*/
